- internal/pkg/apis/apply/v1alpha1/applyconfig_types.go
> API for apply.yaml

- OWNERS
> add approvers

- Makefile
- add license header
- some small improvements
> Some improvements for Makefile

- internal/pkg/status/legacy_status.go
- internal/pkg/status/status_test.go
- internal/pkg/wirecli/wireapply/wire_gen.go
- internal/pkg/wirecli/wirestatus/wire.go
- pkg/cmd.go
1. Fix Succeeded typo
2. Fix go generate failure
> fix generate failure

- site/content/en/installation/krew/bash_zsh.md
Same PR as I just submitted upstream to https://github.com/kubernetes-sigs/krew/pull/656
> Support arm architecture install

- .gitignore
we need to check in docs theme assets and the script
does not appear to create this directory any longer
> stop ignoring vendor directory

- site/content/en/installation/kustomize/binaries.md
Remove the extraneous backslash as it breaks curl
> Remove extraneous backslash

- site/content/en/references/kustomize/kustomization/nameprefix/_index.md
Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>
> Fix Build Output

- site/content/en/references/kustomize/kustomization/replicas/_index.md
This sample code doesn't work, so fixed it.
> Fix kustomize replicas sample code

- site/content/en/references/kustomize/kustomization/patches/_index.md
Improved the documentation of kustomize `patches` field that support a lot of different writing and features.
Added a working example that can be copy & pasted.
Explained some specificities like a label containing a forward slash that need to be escaped which is always the case for Kubernetes recommended labels.
Signed-off-by: Guillaume Le Biller <glebiller@Traveldoo.com>
> Add different strategies examples for kustomize patches fields

- OWNERS
/cc @pwittrock @monopole @natasha41575 
If you agree, I think it would make sense for me to be able to approve changes to Kustomize documentation since I'm an active maintainer. If you'd rather I not have approver for the whole repo, I can look into making separate owners files.
EDIT: I somehow failed at updating my fork--PR is just for me, not also Natasha
> Add Katrina to owners

- site/content/en/references/kubectl/create/job/_index.md
I would like to contribute and provide more api-resources created via `kubectl create` command.
Signed-off-by: Mohit Sharma <imoisharma@icloud.com>
> provide job under kubectl create

- site/content/en/references/kustomize/kustomization/secretgenerator/_index.md
> docs: fix broken link

- site/content/en/guides/introduction/resources_controllers.md
Content is about ConfigMaps vs Secrets.
> Update quoted title to be relevant with content

- site/content/en/references/kustomize/kustomization/generatoroptions/_index.md
Solves https://github.com/kubernetes-sigs/kustomize/issues/4510.
> docs: add immutable flag for generatorOptions

- site/content/en/references/kustomize/kustomization/patchesjson6902/_index.md
Adding some more examples for patchesjson6902 ' operations.
> Add extended examples for patchesjson6902 documentation

- site/content/en/installation/kubectl/binaries.md
Add macOS binary installation instructions.
> Fix issue #260

- site/content/en/references/kustomize/kustomization/configmapgenerator/_index.md
https://github.com/kubernetes-sigs/kustomize/issues/1385
> Note about env single-line limitation

- site/content/en/references/kustomize/kustomization/helmcharts/_index.md
> add more details about helm support to kustomize docs

- site/content/en/references/kustomize/kustomization/labels/_index.md
Documentation for changes introduced in https://github.com/kubernetes-sigs/kustomize/pull/4209
> Add doc for includeSelectors flag

- site/content/en/references/kustomize/kustomization/patches/_index.md
- site/content/en/references/kustomize/kustomization/patchesStrategicMerge/_index.md
We get issues filed about this a lot, so it would be nice to have it clearly stated in the docs.
> Add note about custom resource + SMPs

- CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #295
> Updated README

- site/content/en/references/kustomize/builtins/_index.md
Add documentation for the skipHooks option introduced in kubernetes-sigs/kustomize#4808.
> Document skipHooks helm chart option

- site/content/en/guides/config_management/components.md
Signed-off-by: Aisuko <urakiny@gmail.com>
Hi, teams. this PR fixed some minor issues of `components.md`.
> Remove useless EOF on components.md

- site/content/en/references/kustomize/cmd/localize/_index.md
This PR adds documentation for the `kustomize localize` command.
> Add `kustomize localize` Documentation

- site/content/en/references/kustomize/builtins/_index.md
> Corrected the Typo

- site/content/en/references/kustomize/builtins/_index.md
> Update docs to reflect helmCharts/helmGlobals split from long ago

- OWNERS
related: https://github.com/kubernetes-sigs/kustomize/pull/5518
> Update approver list

- site/content/en/references/kustomize/kustomization/replacements/_index.md
fix https://github.com/kubernetes-sigs/kustomize/issues/5349
/cc @natasha41575
> add warning for regexp match in kustomize replacements
