kubernetes-sigs/cli-experimental

Makefile, go.mod, go.sum, internal/pkg/client/client.go, internal/pkg/client/interface.go, internal/pkg/dy/dy.go, internal/pkg/wirecli/wire.go, internal/pkg/wirecli/wirecli.go, internal/pkg/wirecli/wirek8s/wirek8s.go, internal/pkg/wirecli/wiretest/wiretest.go, scripts/check-everything.sh, scripts/verify.sh
Add support for dynamic client interface.
Can be extended to support typed client if needed later.
Avoiding taking a dependency on controller-runtime which has similar client wrapping over dynamic interface.
=> Adding dynamic-client interface

internal/pkg/resourceconfig/resourceconfig.go, internal/pkg/resourceconfig/resourceconfig_test.go, internal/pkg/wirecli/wireconfig/wireconfig.go, internal/pkg/wirecli/wiretest/wire.go, internal/pkg/wirecli/wiretest/wire_gen.go
add the implementation of `RawConfigFileProvider`.
- When the given path is a file, this provider loads resources from that file
- When the given path is a directory, this provider loads resources from the directory recursively
- The `GetPruneConfig` loads all the resources and returns the one with the inventory annotation
Also added a test to cover
- load resources from a file
- load resources from a directory recursively
- load the inventory resource
TODO: 
So far we have two config providers in this project:
- the kustomize config provider
- the raw config provider
When an argument is given, we need to decide which provider it should use.
This can be checked by the function `IsSupported`.
I'll add the logic to choose the proper config provider in a subsequent PR.
=> implement RawConfigFileProvider

cmd/apply/status/status_test.go, go.mod, go.sum, internal/pkg/apply/apply.go, internal/pkg/delete/delete.go, internal/pkg/prune/prune.go, internal/pkg/resourceconfig/resourceconfig.go, internal/pkg/resourceconfig/resourceconfig_test.go, internal/pkg/wirecli/wireconfig/wireconfig.go, pkg/cmd_test.go
The ordering problem is fixed. Now the order is the same as
the resource presence order in the kustomization.yaml file.
=> update kustomize to 2.1.0 and fix the resource ordering issue

internal/pkg/apply/apply.go, internal/pkg/apply/apply_test.go, internal/pkg/clik8s/clik8s.go, internal/pkg/constants/constants.go, internal/pkg/delete/delete.go, internal/pkg/delete/delete_test.go, internal/pkg/prune/prune.go, internal/pkg/prune/prune_test.go, internal/pkg/resourceconfig/resourceconfig.go, internal/pkg/resourceconfig/resourceconfig_test.go, internal/pkg/util/client_util.go, internal/pkg/wirecli/wireconfig/wireconfig.go, pkg/cmd.go
Add two annotations
```
kubectl.kubernetes.io/presence: PreventDeletion
kubectl.kubernetes.io/presence: EnsureDoesNotExist
```
In apply command, any resource annotated by `EnsureDoesNotExist` won't be applied.
In prune or delete command, any resource annotated by `PreventDeletion` won't be deleted.
=> add support for declarative deletion

.travis.yml, go.mod
travis CI is failing on all PRs with the error:
`../../../pkg/mod/golang.org/x/net@v0.0.0-20210510120150-4163338589ed/http2/client_conn_pool.go:305:6: undefined: errors.Is
note: module requires Go 1.17`
wanted to see if upgrading go would fix it
=> upgrade go

site/content/en/guides/extending_kustomize/builtins.md
- `s/annotions/annotations/`
- remove extraneous "all"
=> Fix typos in builtins.md

site/content/en/references/kustomize/kustomization/configmapgenerator/_index.md
The field is called envs and is a list not env and a string
=> Fix a syntax error in the use of from env file

site/content/en/guides/config_management/components.md
Correct the link to the Kustomize Components KEP page which is currently opening a non-existent page. 
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
=> Update the link to Components KEP page

site/content/en/references/kubectl/apply/_index.md
There's a typo in some of the docs.
=> Fixes misspelling of container.

site/content/en/references/kustomize/kustomization/secretgenerator/_index.md
According to https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets,
the secret needs to have the `tls.crt` key, instead of the `tls.cert` key
=> docs(kustomize-secretgenerator): fix tls secrets

site/content/en/references/kustomize/kustomization/_index.md
There is widespread confusion around the use of apostrophes for pluralization. The rules governing this are really a hot mess, which leads to many misuses. But if you pay careful attention to well-edited documents, you'll almost never see it used. The best rule of thumb is, you never really _need_ them, so it's best to reword your sentences to avoid them entirely.
There are a few valid cases for pluralization with apostrophes, but the whole thing is a general mess so is better avoided when possible. See https://www.dailywritingtips.com/when-to-form-a-plural-with-an-apostrophe/ for a good treatment of the topic.
In this document's example, it's best to just spell out the words for clarity.
=> Minor grammar nits

.gitignore, netlify.toml, site/config.toml, site/content/en/contributing/docs/_index.md, site/netlify.toml
This PR aims to tackle https://github.com/kubernetes-sigs/kustomize/issues/4393
With the added netlify.toml file:
- Changes in the site folder rebuild the site automatically
- Production and Preview site can be configured to use a different hugo version, quite handy for upgrades to hugo version
Once this PR is merged the `docs` folder should not be in use any more and I think it would be good to remove it in another PR.
=> add file-based configuration for netlify

site/content/en/guides/config_management/container_images.md, site/content/en/guides/config_management/labels_annotations.md, site/content/en/guides/config_management/namespaces_names.md, site/content/en/guides/config_management/secrets_configmaps.md
fix broken links in guides which points to references/examples which where moved by this commit (1 year ago!):
https://github.com/kubernetes-sigs/cli-experimental/commit/8e1ef9f7779d172dc6319e616007a396c9d5f973
=> fix broken links in guides

site/content/en/references/kustomize/kustomization/bases/_index.md
This change fixes the resources hyperlink in the kustomize kustomization [bases documentation](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/bases/).
=> site/kustomize: fix resource hyperlink to base

site/content/en/references/kustomize/kustomization/replacements/_index.md
Add docs for replacements to all array elements. (PR merged: https://github.com/kubernetes-sigs/kustomize/pull/4424)
Fix: https://github.com/kubernetes-sigs/kustomize/issues/4053#issuecomment-1034369103
=> docs: replacements to all array elements

site/content/en/references/kustomize/kustomization/replacements/_index.md
Missing escape for the escape (backslash) char in docs.
=> Escape the backslash in docs

site/config.toml, site/i18n/en.toml, site/layouts/partials/footer.html
As per a [slack conversation](https://kubernetes.slack.com/archives/C1J0BPD2M/p1651863457951179), we are updating the copyright text to match [kubernetes.io](https://kubernetes.io). I've added some screenshots of the new copyright in multiple responsive sizes below:
Small
Medium
Large
=> Update copyright to match k8s docs

site/content/en/references/kustomize/builtins/_index.md
Docs for https://github.com/kubernetes-sigs/kustomize/pull/4708 and https://github.com/kubernetes-sigs/kustomize/pull/4704.
Preview is here: https://deploy-preview-290--cli-experimental.netlify.app/references/kustomize/builtins/#usage-via-transformers-field-3
/cc @natasha41575
=> Add docs for new advanced NamespaceTransformer config options

site/content/en/references/kubectl/kustomize/_index.md, site/content/en/references/kustomize/kustomization/namespace/_index.md, site/content/en/references/kustomize/kustomization/namesuffix/_index.md, site/content/en/references/kustomize/kustomization/replicas/_index.md
I believe "container" is intended, not "conatiner".
=> Fix repeated typo in documentation examples

site/content/en/references/kustomize/kustomization/sortoptions/_index.md, site/content/en/references/kustomize/kustomization/vars/_index.md
Kustomize has a new field called "sortOptions" to sort resources: https://github.com/kubernetes-sigs/kustomize/issues/3913 https://github.com/kubernetes-sigs/kustomize/pull/4019
Document what it does and how to use it.
cc @natasha41575
=> Document sortOptions field

site/content/en/references/kustomize/kustomization/bases/_index.md, site/content/en/references/kustomize/kustomization/patchesStrategicMerge/_index.md, site/content/en/references/kustomize/kustomization/patchesjson6902/_index.md, site/content/en/references/kustomize/kustomization/vars/_index.md
Should be merged after release containing the deprecation warnings
/hold
/cc @KnVerey
=> kustomize: add deprecation warning to docs

site/content/en/installation/kustomize/binaries.md
Removes warning about ARM support for Kustomize install script as it is now supported.
Reference: https://github.com/kubernetes-sigs/kustomize/pull/4619.
=> docs: remove warning about ARM support for Kustomize install script

site/content/en/references/kustomize/builtins/_index.md
Hey folks,  I noticed that the four newly added Helm fields were missing from the documentation of Kustomize v5; so I simply added them.
Fields: additionalValuesFiles, skipTests, apiVersions and nameTemplate
Kustomize v5 [release](https://github.com/kubernetes-sigs/kustomize/releases?q=v5.0.0&expanded=true)
=> [Doc] Updating the doc with the newly supported four Helm fields

site/content/en/references/kubectl/scale/_index.md
Correct typo from 'Kubenetes' to 'Kubernetes'.
=> Correct typo from 'Kubenetes' to 'Kubernetes'

site/content/en/faq/kustomize/_index.md
Correct typo from 'Kuberntes' to 'Kubernetes'.
=> Correct typo from 'Kuberntes' to 'Kubernetes'

site/content/en/references/kustomize/kustomization/resource/_index.md
Update kustomize resources remote URL format documentation. This was changed in kustomize but the docs here were never updated.
**Fixes**
https://github.com/kubernetes-sigs/kustomize/issues/5460
=> Update kustomize remote resource URL format docs

site/content/en/references/kustomize/kustomization/helmcharts/_index.md
OCI-based Helm repositories are now supported in Kustomize.
Ref: https://github.com/kubernetes-sigs/kustomize/pull/5167
=> Update _index.md - OCI-based Helm repositories are now supported
